### ISSUE TITLE
No way to clear selection i.e selected files

### ISSUE THREAD

**Issue by shantanuabhosale90** [Richard1320/React-Media-Library#28]
Media library selection is not cleared even if '**defaultSelectedItemIds**' is set to an empty array.

I suggest adding an else block with setSelectedItems([]); in ReactMediaLibrary.tsx line no 17.
So, the updated useEffect hook will be

```
useEffect(() => {
		// Asset loads are sometimes async.
		// Need to check the default and reselect if either the file library list or default select list is updated.
		if (props.defaultSelectedItemIds?.length) {
			const filterDefaultSelected = props.fileLibraryList.filter((item) => props.defaultSelectedItemIds?.includes(item._id));
			setSelectedItems(filterDefaultSelected);
		} else {
			setSelectedItems([]);
		}
	}, [props.fileLibraryList, props.defaultSelectedItemIds]);
```

Please update it so selected items in ReactMediaLibrary can be cleared.

**P.S. Nice component**

Thanks

**Comment by shantanuabhosale90** [comment]
If anyone is looking for a way around for now you can set defaultSelectedItemIds with any value not included in 'fileLibraryList'.
```
e.g 

defaultSelectedItemIds = ["NA"]; //will clear the selection.

```

**Comment by ramonmalcolm10** [comment]
[PR](https://github.com/Richard1320/React-Media-Library/pull/33) raised
