### ISSUE TITLE
Enable Unselection of Selected Files

### ISSUE THREAD

**Issue by ramonmalcolm10** [Richard1320/React-Media-Library#34]
Users are unable to unselect a file if it's the only one selected, once the sole selected file is unselected, the "Select file" button disappears. A possible solution is to track whether any file was selected before the media library open and base on that flag and if all selection was removed then display a "Remove file" button that trigger the ```filesSelectCallback``` function with an empty array.

**Comment by Richard1320** [comment]
Deselect feature is implemented in 2.0.2. If currently selected items is empty but default selected items is not empty, it will display a deselect button that triggers the `filesSelectCallback` function with an empty array.

**Comment by ramonmalcolm10** [comment]
Thanks for the quick implementation, really appreciate it.

**Comment by ramonmalcolm10** [comment]
@Richard1320 the discussion section is not enable hence why am asking this question here. What’s your views around accepting an optional flag that can disable/hide the upload section to prevent user from uploading more than X amount of files?

**Comment by Richard1320** [comment]
> @Richard1320 the discussion section is not enable hence why am asking this question here. What’s your views around accepting an optional flag that can disable/hide the upload section to prevent user from uploading more than X amount of files?

@ramonmalcolm10 Good suggestion. 2.0.3 now changes `filesSelectCallback` and `fileUploadCallback` props to be optional. If undefined, it will hide the browse / upload tab. You can try the [storybook](https://richard1320.github.io/React-Media-Library/?path=/story/react-media-library-reactmedialibrary--disable-upload)
