### ISSUE TITLE
Custom Card Example

### ISSUE THREAD

**Issue by hazem-saeed** [Richard1320/React-Media-Library#36]
I didn't find an example of the custom card to precisely follow. If you could put a working example, that would be really great.
Thank you for your time to create this package.

**Comment by Richard1320** [comment]
If you want to pass in the custom card component, copy the default card component and put it somewhere in your own project.

https://github.com/Richard1320/React-Media-Library/blob/ae2301aa9df29daf6c03010e88003a680b3be938/src/components/FileLibraryCard/FileLibraryCard.tsx#L7

Modify it to your needs and pass it in as the `libraryCardComponent` prop to the <ReactMediaLibrary /> component. It gets passed in as a function with `FileLibraryListItem` as the argument that expects a `ReactElement`.

```typescript
const CustomLibraryCard: React.FC<FileLibraryListItem> = (props: FileLibraryListItem): ReactElement => {
	const {selectedItems} = useContext(ReactMediaLibraryContext);
	const isSelected: boolean = !!selectedItems.find((element) => element._id === props._id);

	return (
		<div>
			This item is {(isSelected) ? "selected" : "not selected"}.
		</div>
	);
}
export const ReactMediaLibraryWrapper = () => {
	const [isOpen, setIsOpen] = useState<boolean>(false);

	return (
		<ReactMediaLibrary
			isOpen={isOpen}
			onClose={() => setIsOpen(false)}
			fileLibraryList={[]}
			libraryCardComponent={(item: FileLibraryListItem) => (<CustomLibraryCard {...item} />)}
		/>
	);
}
```

**Comment by hazem-saeed** [comment]
Thank you for your reply. I ended up creating my own media library, due to my project requirements.
