### ISSUE TITLE
Request for Improvement

### ISSUE THREAD

**Issue by tahafarooqui** [Richard1320/React-Media-Library#5]
Can you add filters, searchbox, scrollbar to fix modal height and attachment details.
Demo: https://prnt.sc/rpo7zh

![download](https://user-images.githubusercontent.com/15617481/77952260-cca9a000-72e4-11ea-9f96-58817ae0b152.png)

**Comment by Richard1320** [comment]
A `topBarComponent` prop component has now been added for search and filters. See https://richard1320.github.io/React-Media-Library/?path=/story/react-media-library-reactmedialibrary--search-bar

A `selectedItemsComponent` prop component has been added for selected items on the sidebar. See https://richard1320.github.io/React-Media-Library/?path=/story/react-media-library-reactmedialibrary--custom-selected-form
